### ISSUE TITLE
Improve error for missing `eventQueue` config

### ISSUE THREAD

**Issue by swaldmann** [cap-js-community/event-queue#242]
Currently the package gives a `TypeError` if you don't add the `cds.eventQueue` config, which might happen as users are used to just `npm add` CAP plugins w/o additional config. The error cannot be easily correlated to the missing config,  so imo at least the error message could be improved.

To reproduce:

1. `cds init bookshop --add tiny-sample`
2. `cd bookshop`
3. `npm add @cap-js-community/event-queue`
4. `cds run --production`

gives you
```sh    
[/eventQueue/plugin] - TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received null
    at readFile (node:fs:387:16)
    at node:internal/util:433:21
    at new Promise (<anonymous>)
    at readFile (node:internal/util:419:12)
    at readConfigFromFile (/Users/D061687/Desktop/bookshop/node_modules/@cap-js-community/event-queue/src/initialize.js:103:28)
    at Object.initialize (/Users/D061687/Desktop/bookshop/node_modules/@cap-js-community/event-queue/src/initialize.js:87:30)
    at Object.<anonymous> (/Users/D061687/Desktop/bookshop/node_modules/@cap-js-community/event-queue/cds-plugin.js:21:31)
    at Module._compile (node:internal/modules/cjs/loader:1546:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1691:10)
    at Module.load (node:internal/modules/cjs/loader:1317:32) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

**Comment by soccermax** [comment]
thanks @swaldmann good catch - will fix that
